### ISSUE TITLE
Monospace font for source-code

### ISSUE THREAD

**Issue by kejace** [f-o-a-m/foam.developer#12]
I like [hasklig](https://github.com/i-tu/Hasklig) but the important part is that it is monospace.

Compare 
<img width="348" alt="screen shot 2018-03-27 at 11 16 57 am" src="https://user-images.githubusercontent.com/586216/37976836-630f5bd4-31b0-11e8-9d33-94364a38e8c0.png">

with

![image](https://user-images.githubusercontent.com/586216/37976879-77f1cc1c-31b0-11e8-89ab-0445f4e58a1c.png)

where we use `Courier`(?).

**Comment by gavinpatkinson** [comment]
Another related issue is that it would be nice to use our GT Haptik font from foam.space. Is there a way we can serve fonts in a more centralized way, like in an AWS bucket? I can ask my font friends about this too.

**Comment by gavinpatkinson** [comment]
I've added a monospace to the foam-hexo-theme-docrepo. now you should be able to just `npm upgrade foam-hexo-theme-doc` to pull the new styles
