### ISSUE TITLE
api query issue

### ISSUE THREAD

**Issue by FergusDevelopmentLLC** [f-o-a-m/foam.developer#17]
i hope this is in the correct repo to post this.
This query is made to to the api in order to get all beacons, some are not returned.

https://api-beta.foam.space/beacon?lon_min=-1000&lat_min=-1000&lon_max=1000&lat_max=1000

For example...
Denver2, Coors Field, PointsDenver, beaconcore don't appear in the result, but are beacons:
https://bl.ocks.org/FergusDevelopmentLLC/0184791f202d731515ec9a315aaef1f7

**Comment by bgoblirsch** [comment]
Also, calling this query returns beacons outside of the provided bounding box:

https://api-beta.foam.space/beacon?lat_min=-105.244904&lon_min=-104.648895&lat_max=39.515695&lon_max=39.985538

It returns most, but not all beacons. Possibly related to the above issue.
