### ISSUE TITLE
Signing the MetaMask transaction failed

### ISSUE THREAD

**Issue by ricburton** [f-o-a-m/foam.developer#23]
<img width="472" alt="screen shot 2018-04-11 at 16 26 57" src="https://user-images.githubusercontent.com/438160/38641516-411ed3fa-3da5-11e8-9609-e262f2119742.png">

I tried to create a beacon on https://beta.foam.space/app but just got a failed transaction.

Could I have done something wrong?

**Comment by safareli** [comment]
Are you on the Rinkeby Test Network?
