### ISSUE TITLE
Prediction Market for Point of Interest Openings / Numerai ErasureBay Integration

### ISSUE THREAD

**Issue by ryan-foamspace** [f-o-a-m/foam.developer#49]
As we move through these unprecedented times, we look forward to seeing which of our favourite businesses have reopened their doors and which have not. Currently, the consensus driven FOAM Map presents an opportunity for a community to verify where Points of Interests exist. This challenge goes deeper to verify another field of information—when the POI is open/closed.

When and/or whether specific points will open is ripe for predictions. We would like to see a map based prediction market for when POI’s will open if at all. This could be a FOAM Map plug-in to an existing prediction market protocol or could be an entirely new innovation.

An exciting integration can be done with Numerai and ErasureBay
https://erasurebay.org/

ErasureBay allows you to Request any information from anyone in the world. Destroy their stake if you don't get what you want.

For this bounty, building a map based interface that pulls FOAM Point of Interest data from on chain and then allows information about the status of the location to be sent to the ErasureBay network or any other kind of prediction market.

Submissions must demonstrate a working and high quality demo. Please communicate the status of your submission once work is approved to start. 

Check out the FOAM Developer Resources post to get started
https://blog.foam.space/foam-dev-resources-9f7fc8967eac

Past Projects for Inspiration
Mapcovery ~ https://devpost.com/software/mapcovery
FOAM Guides and Chat ~ https://github.com/MikaelLazarev/foam-guides/

Use Rinkeby for development! 
https://rink-cd.foam.space/, api at https://rink-cd-api.foam.space/

Reach out to receive FOAM Rinkeby tokens for testing

**Comment by Solexplorer** [comment]
@ryan-foamspace The bounty says: 

> Submissions must demonstrate a working and high quality demo. Submissions must be received by May 27th.

Can you update it with the correct date? 
Thanks

**Comment by ryan-foamspace** [comment]
@Solexplorer thanks, updated. There is no strict deadline once approved to start work on the bounty.
